version: "3.7"
services:
  dyndns-update:
    container_name: dyndns-update
    restart: unless-stopped
    image: tknorris/dyndns-updater
    env_file: updater.env
    volumes:
      - /Users/tknorris/workspace/dyndns-update:/config